### ISSUE TITLE
Fix deleting data on controller

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#112]
following issue occurring when deleting an item. identify how this can be occurred and fix it

![image](https://github.com/user-attachments/assets/bab0e1d4-4a7e-4312-b364-f6c790ccf8da)

**Comment by aanish27** [comment]
![image](https://github.com/user-attachments/assets/16480193-19ff-4c7c-9ecd-29381272241e)
Couldn't find this on my PC above is the code...it seems fine too as I'm accessing the projects relationship before deleting the modal...please check with the issue again...attached the response for ur reference... @Raza9798 

![image](https://github.com/user-attachments/assets/5e3c90a0-c0c9-4200-951e-0671517c6d29)

![image](https://github.com/user-attachments/assets/684f79ca-b2c9-44ec-9b98-ac1e288048a9)

**Comment by Raza9798** [comment]
The data I choose to delete was below
![image](https://github.com/user-attachments/assets/dc8e282b-ffb8-424c-9b5c-64ccfb07d9fa)

Once I delete the data it shows me 500 as you can see on the image
![image](https://github.com/user-attachments/assets/a94361be-302d-4dc1-9df1-4d5036c7548a)

Following is the response I received 
![image](https://github.com/user-attachments/assets/f97bd2fb-a4ef-4409-b5b4-3849a3a3c53d)

Identify what makes this issue. client's won't work as how you implemented. for example just think you made that red plastic thing to put on the specific whole. but it can be placed between any of the whole. if it doesn't make issues, no worries. but if it makes you have to consider that what you did can be makes errors

![image](https://github.com/user-attachments/assets/531a6189-bcc7-4100-802b-bc86c4c75297)

**Comment by Raza9798** [comment]
it makes a new issue now
![image](https://github.com/user-attachments/assets/98e20a09-29a9-426f-a980-ae73bee0c823)

Please fix it

**Comment by aanish27** [comment]
Im genuinely curios how this error occurs and how to debug them....here ur testing on a different environment and finding these bugs but now lets assume a solo developer how would he find these bugs cause "it works fine on their computer" whats the real world approach?

Also please explain this too i have attached the code too....and it also seems fine nah  cuz i have taken the instance and assigned to a variable and and im deleting calling the modal which means it has nothing to do with the instance then how could this occur? what am i missing please be kind enough enlighten me with ur generous knowledge.... @Raza9798 
 
![image](https://github.com/user-attachments/assets/6d3a125a-19a5-4745-bed8-24dcbda60218)
![image](https://github.com/user-attachments/assets/6d3a125a-19a5-4745-bed8-24dcbda60218)

**Comment by Raza9798** [comment]
lets take a real world example, User A and User B are working on employee module and User B deleting in-active employees from their login portal. at the same time User A deleting the employee who are no longer at work place, the scenario is  a same employee can be in-active and no longer at work place. the issue occurs when process matches this scenario.
