### ISSUE TITLE
Define foreign & primary key in relationships

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#113]
Define foreign & primary key in relationships all the models

![image](https://github.com/user-attachments/assets/c759b948-aa27-4ff8-9993-01301600f548)

**Comment by aanish27** [comment]
#116 PR created

**Comment by Raza9798** [comment]
Please enter both keys

**Comment by aanish27** [comment]
> Please enter both keys

Yeah sure did please review again #116 @Raza9798
