### ISSUE TITLE
fix deleting a company removing all the employees

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#56]
Once we delete a company it removes the all users who are belong to that specific company. that should not be happen in our systems.

_Originally posted by @Raza9798 in https://github.com/axnish27/employee-profile-manager/issues/46#issuecomment-2383433460_

**Comment by axnish27** [comment]
okay sure...read a post saying its bad practice to use cascade on delete and we should use soft delete instead, is it? @Raza9798

**Comment by axnish27** [comment]
> even if you delete the company all employee should be exists. that's how the system should work. @axnish27

got it.. implemented and created PR please check #57

**Comment by Raza9798** [comment]
when editing a data these fields are getting empty. please check and fix @axnish27 

![image](https://github.com/user-attachments/assets/c7c3241b-497d-45d1-9c75-52b306b829b3)

**Comment by axnish27** [comment]
Sure...i checked and fixed please review the PR again @Raza9798

**Comment by Raza9798** [comment]
https://github.com/axnish27/employee-profile-manager/pull/57#pullrequestreview-2338603840 please have look and make a reply comments @axnish27

**Comment by axnish27** [comment]
Replied to all the comments pleaser review again @Raza9798 #57

**Comment by Raza9798** [comment]
mentioned to resolve the issue https://github.com/axnish27/employee-profile-manager/pull/57 @axnish27

**Comment by axnish27** [comment]
> mentioned to resolve the issue #57 @axnish27

Resolved the issues please review again @Raza9798 #57

**Comment by aanish27** [comment]
> the application allowing user to change the deleted company. Please fix it
> 
> ![image](https://private-user-images.githubusercontent.com/59387235/372526730-71bc4d5c-67f3-4f03-a930-53f7518ed8cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDEwNDQsIm5iZiI6MTcyNzgwMDc0NCwicGF0aCI6Ii81OTM4NzIzNS8zNzI1MjY3MzAtNzFiYzRkNWMtNjdmMy00ZjAzLWE5MzAtNTNmNzUxOGVkOGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE2MzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NWIyMDRhZGJhYmMzNzZhYjI4Y2VlM2M5MGQ4YzhjNWMyNDk0NDAyYmI5MGFiZDA0OWI0NzAzNWI0MGM2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M9taCau83XLWMsR8CiPIfBAx73rlIqu51mMVAIegBHs)

Fixed please review again @Raza9798 #57
