### ISSUE TITLE
setup login credentials as default on blade

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#58]
![image](https://github.com/user-attachments/assets/eb206fbb-f2ed-4e0a-a334-504d0bbc69f2)

**Comment by axnish27** [comment]
Default user implemented and created a PR please review @Raza9798 #59

**Comment by Raza9798** [comment]
https://github.com/axnish27/employee-profile-manager/pull/59 revert the changes to previous state. making a default user via factories and seeders are correct. what I assign is to set values on blade for easy login without typing the credentials every time. since this is a practice set the email and password on respective fields @axnish27

**Comment by aanish27** [comment]
> #59 revert the changes to previous state. making a default user via factories and seeders are correct. what I assign is to set values on blade for easy login without typing the credentials every time. since this is a practice set the email and password on respective fields @axnish27


Yes got it...re-implemented as you mentioned please review again @Raza9798 #59

**Comment by Raza9798** [comment]
https://github.com/aanish27/employee-profile-manager/pull/59 requested changes
