### ISSUE TITLE
Fix the datatable layout and component

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#60]
![image](https://github.com/user-attachments/assets/5893c807-7db8-4ad5-9da8-4f63c8e6d718)

properly align the datatable component following is the reference image
![image](https://github.com/user-attachments/assets/25274b8e-8ec7-46ea-a13e-1d0a1fc602d7)

**Comment by aanish27** [comment]
Fixed and created a PR #62 please review

**Comment by Raza9798** [comment]
![image](https://github.com/user-attachments/assets/d5bce3ce-b8b4-4fb3-b2dd-4f02f048a9d0)

once we have 50 data on the datatable. page should not be scrolled to down instead datatable should scolled up and down. fix it

**Comment by aanish27** [comment]
> ![image](https://private-user-images.githubusercontent.com/59387235/372919017-d5bce3ce-b8b4-4fb3-b2dd-4f02f048a9d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTk1NzAsIm5iZiI6MTcyODA1OTI3MCwicGF0aCI6Ii81OTM4NzIzNS8zNzI5MTkwMTctZDViY2UzY2UtYjhiNC00ZmIzLWIyZGQtNGYwMmYwNDhhOWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDE2Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2M2QxZTE4MGM5ZmUwZDRiZmNiMzk5YWEyZmUwMTg0MDA1NzBiNWU2ZjRkMzBkZGI2ZjIwZTZjNmRhZTc4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aWS4Ms_4GO7S2j2-xFmvTpG1-7b0CALCU1Nxd6L3ymw)
> 
> once we have 50 data on the datatable. page should not be scrolled to down instead datatable should scolled up and down. fix it

as advised implemented please review @Raza9798

**Comment by Raza9798** [comment]
https://github.com/aanish27/employee-profile-manager/pull/62#pullrequestreview-2348503538 changes requested

**Comment by aanish27** [comment]
> #62 (review)

Requested changes have been added please review @Raza9798  #62 

![image](https://github.com/user-attachments/assets/5fcddc2e-450a-44b3-9b90-9691a58cb7ca)

**Comment by Raza9798** [comment]
https://github.com/aanish27/employee-profile-manager/pull/62#pullrequestreview-2348731664 changes requested

**Comment by Raza9798** [comment]
https://github.com/aanish27/employee-profile-manager/pull/62#pullrequestreview-2349024589 requested changes

**Comment by aanish27** [comment]
> [#62 (review)](https://github.com/aanish27/employee-profile-manager/pull/62#pullrequestreview-2349024589) requested changes

Completed requested changes @Raza9798 Please review again #62

**Comment by Raza9798** [comment]
https://github.com/aanish27/employee-profile-manager/pull/62#pullrequestreview-2352149709. requested changes

**Comment by aanish27** [comment]
> [#62 (review)](https://github.com/aanish27/employee-profile-manager/pull/62#pullrequestreview-2348731664) changes requested

Changes implemented review please @Raza9798  #62

**Comment by Raza9798** [comment]
https://github.com/aanish27/employee-profile-manager/pull/62#discussion_r1790727113 changes requested

**Comment by Raza9798** [comment]
https://github.com/aanish27/employee-profile-manager/pull/62#discussion_r1790752854 changes requested
