### ISSUE TITLE
fix UI issues

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#75]

**Comment by aanish27** [comment]
![image (7)](https://github.com/user-attachments/assets/33821f01-339d-4031-966f-02ac3d66ee1c)

Fix button

**Comment by aanish27** [comment]
![image (8)](https://github.com/user-attachments/assets/4105e303-4c93-4839-b975-d6ddb88303e4)

remove the search element
place the title at search element position

**Comment by aanish27** [comment]
above issues are fixed and created a PR #76  @Raza9798

**Comment by Raza9798** [comment]
![image](https://github.com/user-attachments/assets/084ca690-51b9-4c09-85e4-b2d8c0f913b2)

once you create PR make sure you done the changes in all modules

**Comment by Raza9798** [comment]
![image](https://github.com/user-attachments/assets/19b8560d-bfc6-49ec-8c9d-d881b17c69e2)

this blue button looks nice add a icon at the start position

**Comment by aanish27** [comment]
Yeah sure...
> once you create PR make sure you done the changes in all modules

**Comment by aanish27** [comment]
> add a icon at the start position

Okay sure

**Comment by Raza9798** [comment]
![image](https://github.com/user-attachments/assets/643b1784-5606-45b7-b952-631f9dbda5ce)

Models should have proper header and footer

**Comment by Raza9798** [comment]
![image](https://github.com/user-attachments/assets/e7ee5e7d-92f2-44d1-845d-0a801fd66861)

add a logout button on the topbar

**Comment by Raza9798** [comment]
![image](https://github.com/user-attachments/assets/3d1e2aa3-efd3-45ec-b126-cd34aee7b308)

add datatable ordering feature

**Comment by aanish27** [comment]
> add datatable ordering feature

Resolved @Raza9798  #76

**Comment by Raza9798** [comment]
![image](https://github.com/user-attachments/assets/de3496b3-ccd4-46d6-99bd-56083d1fa131)

**modal is popup at center of the screen place the modal at top side** so it will make easier when data entry happens

**Comment by aanish27** [comment]
> **modal is popup at center of the screen place the modal at top side** so it will make easier when data entry happens
Resolved please review again @Raza9798 #76
