### ISSUE TITLE
Datatable Ordering fix

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#79]
![image](https://github.com/user-attachments/assets/3d1e2aa3-efd3-45ec-b126-cd34aee7b308)

add datatable ordering feature and Use Eloquent query to order in MySQL not in array

_Originally posted by @Raza9798 in https://github.com/aanish27/employee-profile-manager/issues/75#issuecomment-2427582092_

**Comment by aanish27** [comment]
this branch acts like a parent branch to #80 and #81....when working on this branch i have make changes to both then when working on those branches i have to make changes separately...this process makes a big mess... i think its better if we merged #85 and #86 to #83... @Raza9798

**Comment by Raza9798** [comment]
put the PR links which are needs to be merged

**Comment by aanish27** [comment]
> put the PR links which are needs to be merged

https://github.com/aanish27/employee-profile-manager/pull/86
https://github.com/aanish27/employee-profile-manager/pull/85
