### ISSUE TITLE
Converting Controllers from Query builder to ORM

### ISSUE THREAD

**Issue by Raza9798** [aanish27/employee-profile-manager#93]
![image](https://github.com/user-attachments/assets/70f40a50-e402-4ebf-87cc-78713c1e2279)

remove joint queries and use Eloquent ORM

**Comment by aanish27** [comment]
![image](https://github.com/user-attachments/assets/f1d10977-6d77-47dd-b881-56263b8331f2)

is this the way? @Raza9798
